server.port=${PORT:8080}

spring.application.name=youtube-mp3-backend

app.tools.yt-dlp=${YT_DLP_PATH:yt-dlp}
app.tools.ffmpeg=${FFMPEG_PATH:ffmpeg}
app.download-dir=${DOWNLOAD_DIR:downloads}

app.frontend-url=${FRONTEND_URL:http://localhost:5173}